Gunnum=7

[StripperRED_1]
DamagePerMinute=57820.261437908
DamagePerMagazine=7038.75
DamagePerSecond=281.55
TimeSpentReloading=9.8
TimeSpentShooting=43.75
[LoneStarRED_2]
DamagePerMinute=234634.9466776
DamagePerMagazine=17655.555555556
DamagePerSecond=706.22222222222
TimeSpentReloading=28.6
TimeSpentShooting=30.0925925925932592592593
[RIA30StrikeForceRED_3]
DamagePerMinute=330157.71428571
DamagePerMagazine=38438.4
DamagePerSecond=3203.2
TimeSpentReloading=8
TimeSpentShooting=48
[CM451StarburstRED_4]
DamagePerMinute=89385
DamagePerMagazine=42606.85
DamagePerSecond=193.6675
TimeSpentReloading=2.2
TimeSpentShooting=55
[StripperRED_5]
DamagePerMinute=57820.261437908
DamagePerMagazine=7038.75
DamagePerSecond=281.55
TimeSpentReloading=9.8
TimeSpentShooting=43.75
[MixMasterIncorrectlyInputted_6]
DamagePerMinute=54993.040089087
DamagePerMagazine=11551.754385965
DamagePerSecond=88.859649122807
TimeSpentReloading=4.8
TimeSpentShooting=45.6140350877194035087719
[MixMaster_7]
DamagePerMinute=109986.08017817
DamagePerMagazine=23103.50877193
DamagePerSecond=177.71929824561
TimeSpentReloading=4.8
TimeSpentShooting=45.614035087719
