Gunnum=4

[Gun_1]
DamagePerMinute=10747.826086957
DamagePerMagazine=2060
DamagePerSecond=34.333333333333
TimeSpentReloading=7.5
TimeSpentShooting=50
[Gun_2]
DamagePerMinute=257142.85714286
DamagePerMagazine=22500
DamagePerSecond=1500
TimeSpentReloading=16.5
TimeSpentShooting=41.25
[Gun_3]
DamagePerMinute=10747.826086957
DamagePerMagazine=2060
DamagePerSecond=34.333333333333
TimeSpentReloading=7.5
TimeSpentShooting=50
[Gun_4]
DamagePerMinute=10747.826086957
DamagePerMagazine=2060
DamagePerSecond=34.333333333333
TimeSpentReloading=7.5
TimeSpentShooting=50