# This is the global settings of the calculator.
[GLOBAL_SETTINGS]
# These are meant to be quality of life options.
AllAtOnce = false # Input all numbers at once or one by one?
FileUsage = false # NOT IMPLEMENTED
Logging = true # NOT IMPLEMENTED
NameLogs = false # NOT IMPLEMENTED
DefaultIn = false # NOT IMPLEMENTED
DefaultOut = false # NOT IMPLEMENTED

[CALCULATION]
# You can choose what values to calculate and ignore.
DamagePerMag = true # Damage per magazine
DamagePerMinute = true # Damage per minute
DamagePerSecond = true # Damage per second
TimeSpentReloading = true # How many seconds of reloading per minute IMPLEMENTED, BUT INACCURATE
TimeSpentShooting = true # How many seconds of shooting per minute IMPLEMENTED, BUT INACCURATE
OneZombie = false # Calculate damage for one zombie or for multiple? NOT IMPLEMENTED
OneProjectile = false # Calculate the damage of a single projectile or all of the projectiles? NOT IMPLEMENTED