Gunnum=19

[StripperRED_1]
DamagePerMinute=57820.261437908
DamagePerMagazine=7038.75
DamagePerSecond=281.55
TimeSpentReloading=9.8
TimeSpentShooting=43.75

[LoneStarRED_2]
DamagePerMinute=234634.9466776
DamagePerMagazine=17655.555555556
DamagePerSecond=706.22222222222
TimeSpentReloading=28.6
TimeSpentShooting=30.0925925925932592592593

[RIA30StrikeForceRED_3]
DamagePerMinute=330157.71428571
DamagePerMagazine=38438.4
DamagePerSecond=3203.2
TimeSpentReloading=8
TimeSpentShooting=48

[CM451StarburstRED_4]
DamagePerMinute=89385
DamagePerMagazine=42606.85
DamagePerSecond=193.6675
TimeSpentReloading=2.2
TimeSpentShooting=55

[StripperRED_5]
DamagePerMinute=57820.261437908
DamagePerMagazine=7038.75
DamagePerSecond=281.55
TimeSpentReloading=9.8
TimeSpentShooting=43.75

[MixMasterIncorrectlyInputted_6]
DamagePerMinute=54993.040089087
DamagePerMagazine=11551.754385965
DamagePerSecond=88.859649122807
TimeSpentReloading=4.8
TimeSpentShooting=45.6140350877194035087719

[MixMaster_7]
DamagePerMinute=109986.08017817
DamagePerMagazine=23103.50877193
DamagePerSecond=177.71929824561
TimeSpentReloading=4.8
TimeSpentShooting=45.614035087719

[PhantomRED_8]
DamagePerMinute=14707.75862069
DamagePerMagazine=1203.5978835979
DamagePerSecond=21.883597883598
TimeSpentReloading=24
TimeSpentShooting=34.920634920635

[Ria20DSC_RED_9]
DamagePerMinute=107898.38709677
DamagePerMagazine=18582.5
DamagePerSecond=265.46428571429
TimeSpentReloading=10
TimeSpentShooting=41.666666666667

[RonsonWPFlamethrower_10]
DamagePerMinute=37322.033898305
DamagePerMagazine=12133.333333333
DamagePerSecond=48.533333333333
TimeSpentReloading=9
TimeSpentShooting=50

[CM351SunflareRED_11]
DamagePerMinute=65602.885821832
DamagePerMagazine=20395.053191489
DamagePerSecond=123.60638297872
TimeSpentReloading=3.3
TimeSpentShooting=52.659574468085

[CM440TitanRED_12]
DamagePerMinute=76828.651685393
DamagePerMagazine=11396.25
DamagePerSecond=189.9375
TimeSpentReloading=8.4
TimeSpentShooting=45

[CM505RED_13]
DamagePerMinute=78030.456852792
DamagePerMagazine=27949.090909091
DamagePerSecond=120.99173553719
TimeSpentReloading=4.8
TimeSpentShooting=38.181818181818

[CM530BabyCOMRED_14]
DamagePerMinute=141205.97014925
DamagePerMagazine=15768
DamagePerSecond=262.8
TimeSpentReloading=13.6
TimeSpentShooting=40

[Ronson50RED_15]
DamagePerMinute=89381.25
DamagePerMagazine=9534
DamagePerSecond=211.86666666667
TimeSpentReloading=12.6
TimeSpentShooting=45

[HVMOO8RED_16]
DamagePerMinute=65616.104395326
DamagePerMagazine=28080
DamagePerSecond=156
TimeSpentReloading=4.6
TimeSpentShooting=46.753246753247

[IncorrectlyInputtedRiaT40_17]
DamagePerMinute=48698.843930636
DamagePerMagazine=14041.5
DamagePerSecond=117.0125
TimeSpentReloading=6.9
TimeSpentShooting=45

[RiaT40_18]
DamagePerMinute=49219.075144509
DamagePerMagazine=14041.5
DamagePerSecond=117.0125
TimeSpentReloading=6.9
TimeSpentShooting=45

[Ria20StrikerRED_19]
DamagePerMinute=96382.75862069
DamagePerMagazine=23042.5
DamagePerSecond=460.85
TimeSpentReloading=8
TimeSpentShooting=50
