Gunnum=5

[Ronson_55_1]
DamagePerMinute=15950.27700831
DamagePerMagazine=1827.9523809524
DamagePerSecond=15.895238095238
TimeSpentReloading=12.216066481994
TimeSpentShooting=47.783933518006

[Sublight_COM2_2]
DamagePerMinute=198970.43478261
DamagePerMagazine=38136
DamagePerSecond=762.72
TimeSpentReloading=7.8260869565217
TimeSpentShooting=52.173913043478

[T_102_Jagdfaust_3]
DamagePerMinute=497426.08695652
DamagePerMagazine=95340
DamagePerSecond=3178
TimeSpentReloading=7.8260869565217
TimeSpentShooting=52.173913043478

[Mixmaster_4]
DamagePerMinute=116196.54788419
DamagePerMagazine=24408.070175439
DamagePerSecond=187.75438596491
TimeSpentReloading=5.7126948775056
TimeSpentShooting=54.287305122494

[Stripper_RED_5]
DamagePerMinute=66264.705882353
DamagePerMagazine=8448.75
DamagePerSecond=337.95
TimeSpentReloading=10.980392156863
TimeSpentShooting=49.019607843137
